# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master
- experiment

pool:
  vmImage: 'ubuntu-16.04'

stages:
- stage: A
  jobs:
  - job: A1
    steps:
    - bash: echo "A1"
  - job: A2
    steps:
    - bash: echo "A2"

- stage: B
  jobs:
  - job: B1
  steps:
    - bash: echo "A2"
  - job: B2
  steps:
    - bash: echo "A2"
